bank_token: <%= ENV["BANK_TOKEN"] %>
payment_bank_url: <%= ENV["PAYMENT_BANK_URL"] %>
order_bank_url: <%= ENV["ORDER_BANK_URL"] %>
zezo: 0
max_char: 200
tour: 10
review: 10
booking:
  error: Sorry! system error
payment:
  not_sign_in: 1
  booking_not_found: 3
  system_error: 4
limitdepth: 2
image_tour: 1200x300
gravatar: 50x50
default_image_tour: "fire.png"
rate_min: 0
rate_max: 5
roud_rate: 1
limit_category: 10
format_date: "%Y%m%d"
